### ISSUE TITLE
Any documentation or controller examples?

### ISSUE THREAD

**Issue by paumarquez** [AndrePatri/MPCHive#1]
Hello,

Thank you very much for this implementation, it was right what I was looking for!

Do you have any examples of simple controllers using CoClusterBridge, or any high level documentation on how to use this library?

Thanks in advance.

Best,
Pau

**Comment by AndrePatri** [comment]
Hi @paumarquez ,
Thanks for the interest. 
Currently, I am using the package within [LRHControl](https://github.com/AndrePatri/LRHControl). There you can find some implementations for the cluster and client, and also an outdated example of a very stupid rhc controller which I used just for testing in an intial phase. The controller I am using right know is not open source, so you cannot access it. Overall the approach for writing controller is always the same (i.e. implement of the abstract methods of the parent class). Unfortunately, I am the only one developing the software ecosystem, and I currently I have 0 time to write a decent documentation. However, feel free to come back at me with any doubt.

**Comment by paumarquez** [comment]
Thank you very much Andrea.
I have been digging in the project and I think I have a good feeling of how it works.
I ran it with my MPC controller and it works very well!
Thanks for making this project public :)
